version: '3'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"  # do testów lokalnie
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    # Nie trzeba pushować oficjalnego postgres, pulluje się na serwerze

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: sebastiankociuba/node-backend:latest  # 🔑 potrzebne dla docker-compose push
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydb
    ports:
      - "3001:3000"
    depends_on:
      - db

volumes:
  db-data:
