version: '3'

services:
  db:
    image: postgres:15    # jest gotowy image z dockerhub
    environment:
      POSTGRES_USER: ${POSTGRES_USER}           # wartości czytane z pliku .env (nie commitujemy haseł do repo)
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data        # prawe strony na sztywno
      - ./sql:/docker-entrypoint-initdb.d       # lewe strony zależą od volumes:db-data: a ./sql bo tak nazywa się folder w projekcie i możesz to zmieniać
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}   # czeka aż postgres faktycznie akceptuje połączenia, nie tylko że kontener się uruchomił
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: sebastiankociuba/node-backend:latest   # obraz z Docker Hub, budowany przez GitHub Actions
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"   # db to nazwa serwisu powyżej
    ports:
      - “3001:3000”   # lewa: port na hoście/VPS, prawa: port wewnątrz kontenera
    depends_on:
      db:
        condition: service_healthy   # app startuje dopiero gdy healthcheck bazy przejdzie

volumes:
  db-data:   # nazwa wolumenu - dane bazy przeżywają restart kontenerów
